"""update model compensation

Revision ID: 2098320a7ba9
Revises: 4176d2536a67
Create Date: 2025-03-27 12:33:00.180609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2098320a7ba9'
down_revision: Union[str, None] = '4176d2536a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
