"""update model compensation2

Revision ID: 962e6edfe2e7
Revises: 2098320a7ba9
Create Date: 2025-03-27 12:42:11.779646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "962e6edfe2e7"
down_revision: Union[str, None] = "2098320a7ba9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancies", "compensation", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancies", "compensation", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
